# Generated by Django 4.1.4 on 2023-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_ID', models.CharField(max_length=255)),
                ('function_ID', models.CharField(max_length=255)),
                ('eventId', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_ID', models.CharField(max_length=255)),
                ('phone_brand', models.CharField(max_length=255)),
                ('voice_ID', models.CharField(max_length=255)),
            ],
        ),
    ]
