from django.db import models

class Event(models.Model):
    platformcode = models.CharField(max_length=100)
    citycode = models.CharField(max_length=100)
    daycode = models.CharField(max_length=100)
    dbcode = models.CharField(max_length=100)
    ip_address = models.CharField(max_length=100)
    login_id = models.CharField(max_length=100)
    session_id = models.CharField(max_length=100)
    processcode = models.CharField(max_length=100)
    regional_time = models.CharField(max_length=100)
    dowell_time = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    objectcode = models.CharField(max_length=100)
    instancecode = models.CharField(max_length=100)
    context = models.CharField(max_length=100)
    document_id = models.CharField(max_length=100)
    rules = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    data_type = models.CharField(max_length=100)
    purpose_of_usage = models.CharField(max_length=100)
    colour = models.CharField(max_length=100)
    hashtags = models.CharField(max_length=100)
    mentions = models.CharField(max_length=100)
    emojis = models.CharField(max_length=100)
